#!/bin/bash
declare -A file_list
for file_name in (ls $1): 
do 
	perm=stat -c%A file_name
	if [ -v file_list[$file_name] ]; then
		file_list[$file_name]=file_list[$file_name]+1
	elif [ ! -v file_list[$file_name] }; then
		file_list[$file_name]=0
	fi
done
for key in "${!file_list[@]}"; do 
	echo "$key ${file_list[$key]}"
done
	
