#!/bin/bash
if test $# -eq 0 then
	echo "Usage: $) ordinary_file" exit 1
fi
if test $# -gt 1 then 
	echo "Usage:$0 ordinary_file" exit 1
fi
if test -f "$1" then 
	filename=$1
	set -- 'ls -l $filename'
	perms="$1"
	size="$5"
	set 'ls -i $filename'
	inode="$1"
	echo "File name:	$filename"
	echo "Inode Number:	$inode"
	echo "Permissions: 	$perms"
	echo "Size (bytes):	$size"
	exit 0
fi
echo "$0: argument must be an ordinary file" exit 1

